# Generated by Django 6.0 on 2026-01-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_ilmiy_ishlari_haqida'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='gmail',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
