# Generated by Django 6.0 on 2026-01-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_foydalanuvchilar_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='haqida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
