# Generated by Django 6.0 on 2026-01-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_foydalanuvchilar_haqida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiy_ishlari',
            name='foreverone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oquvishlari',
            name='foreveryone',
            field=models.BooleanField(default=False),
        ),
    ]
