# Generated by Django 6.0 on 2026-01-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_ilmiy_ishlari_foreverone_oquvishlari_foreveryone'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='ilmiy_daraja',
            field=models.CharField(blank=True, default='Bakalavr', max_length=250),
        ),
    ]
