# Generated by Django 6.0 on 2026-01-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_foydalanuvchilar_ilmiy_daraja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilmiy_ishlari',
            old_name='foreverone',
            new_name='foreveryone',
        ),
    ]
