# Generated by Django 6.0 on 2026-01-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_foreverone_ilmiy_ishlari_foreveryone'),
    ]

    operations = [
        migrations.AddField(
            model_name='oquvishlari',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='oquv_ishlari_images/'),
        ),
    ]
