# Generated by Django 6.0 on 2026-01-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_oquvishlari_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='oquvishlari',
            name='haqida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
