# Generated by Django 5.2.9 on 2026-02-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_oquvishlari_haqida'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_darslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
                ('haqida', models.TextField(blank=True, null=True)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foydalanuvchilar')),
            ],
        ),
    ]
