# Generated by Django 6.0 on 2026-02-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_video_darslar'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_darslar',
            name='video',
            field=models.FileField(default=1, upload_to='video_darslar/'),
            preserve_default=False,
        ),
    ]
