# Generated by Django 6.0 on 2026-02-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_video_darslar_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_darslar',
            name='sana',
            field=models.DateField(null=True),
        ),
    ]
