# Generated by Django 6.0 on 2026-02-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_video_darslar_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_darslar',
            name='foreveryone',
            field=models.BooleanField(default=False),
        ),
    ]
