# Generated by Django 5.2.9 on 2026-03-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_video_darslar_foreveryone'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
