# Generated by Django 5.2.9 on 2026-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_foydalanuvchilar_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
