# Generated by Django 5.2.9 on 2026-03-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_foydalanuvchilar_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foydalanuvchilar',
            name='email_sent',
        ),
    ]
