# Generated by Django 5.2.9 on 2026-03-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_foydalanuvchilar_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='created',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
