# Generated by Django 6.0.3 on 2026-09-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_foydalanuvchilar_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafedraTalablari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=300)),
                ('ish_turi', models.CharField(choices=[('Scopus', 'Scopus maqola'), ('Maqola', 'OAK / Xalqaro maqola'), ('Tezis', 'Tezis / Konferensiya'), ('Darslik', 'Darslik'), ('O`quv qo`llanma', 'O`quv qo`llanma'), ('Monografiya', 'Monografiya'), ('Uslubiy ko`rsatma', 'Uslubiy ko`rsatma'), ('EHM guvohnomalar', 'EHM / Patent'), ('Boshqa', 'Boshqa vazifa')], default='Maqola', max_length=100)),
                ('talab_miqdori', models.PositiveIntegerField(default=1, help_text="Har bir o'qituvchidan talab qilinadigan soni")),
                ('muddati', models.DateField(blank=True, null=True)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('faol', models.BooleanField(default=True)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, null=True)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talablar', to='app.kafedralar')),
                ('mudir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuklagan_talablari', to='app.foydalanuvchilar')),
            ],
            options={
                'ordering': ['-yaratilgan_sana'],
            },
        ),
    ]
