# Generated by Django 4.2.30 on 2026-09-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_kafedratalablari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dekanatlar',
            options={'verbose_name': 'Fakultet', 'verbose_name_plural': 'Fakultetlar'},
        ),
        migrations.AlterModelOptions(
            name='foydalanuvchilar',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='ilmiy_ishlari',
            options={'verbose_name': 'Ilmiy ish', 'verbose_name_plural': 'Ilmiy ishlar'},
        ),
        migrations.AlterModelOptions(
            name='kafedralar',
            options={'verbose_name': 'Kafedra', 'verbose_name_plural': 'Kafedralar'},
        ),
        migrations.AlterModelOptions(
            name='kafedratalablari',
            options={'ordering': ['-yaratilgan_sana'], 'verbose_name': 'Kafedra talabi', 'verbose_name_plural': 'Kafedra talablari'},
        ),
        migrations.AlterModelOptions(
            name='oquvishlari',
            options={'verbose_name': "O'quv ishi", 'verbose_name_plural': "O'quv ishlari"},
        ),
        migrations.AlterModelOptions(
            name='video_darslar',
            options={'verbose_name': 'Video dars', 'verbose_name_plural': 'Video darslar'},
        ),
        migrations.AlterField(
            model_name='dekanatlar',
            name='dekan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dekan', to='app.foydalanuvchilar', verbose_name='Dekan'),
        ),
        migrations.AlterField(
            model_name='dekanatlar',
            name='kafedralar',
            field=models.ManyToManyField(blank=True, related_name='dekanat_kafedralari', to='app.kafedralar', verbose_name='Kafedralar'),
        ),
        migrations.AlterField(
            model_name='dekanatlar',
            name='nomi',
            field=models.CharField(max_length=250, verbose_name='Fakultet nomi'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='fakulteti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fakulteti', to='app.dekanatlar', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='familiya',
            field=models.CharField(max_length=250, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='foydalanuvchi_rol',
            field=models.CharField(choices=[('prorektor', 'Prorektor'), ('dekan', 'Dekan'), ('kafedra mudiri', 'Kafedra mudiri'), ('oqituvchi', 'Oqituvchi')], max_length=50, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='gmail',
            field=models.EmailField(max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='haqida',
            field=models.TextField(blank=True, null=True, verbose_name="Qisqacha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='ilmiy_daraja',
            field=models.CharField(blank=True, default='Bakalavr', max_length=250, verbose_name='Ilmiy daraja'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foydalanuvchilar/', verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='ism',
            field=models.CharField(max_length=250, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='kafedra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foydalanuvchilari', to='app.kafedralar', verbose_name='Kafedra'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='login_f',
            field=models.CharField(max_length=250, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='parol',
            field=models.CharField(max_length=250, verbose_name='Parol (xeshlangan)'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='sharifi',
            field=models.CharField(max_length=250, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='tugulgan_sana',
            field=models.DateField(verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='fayl',
            field=models.FileField(upload_to='ilmiy_ishlari/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='foreveryone',
            field=models.BooleanField(default=False, verbose_name="Hamma ko'ra oladi"),
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='haqida',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='ish_mualliflari',
            field=models.TextField(null=True, verbose_name='Hammualliflar'),
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='kategoriya',
            field=models.CharField(choices=[('Xalqaro', 'Xalqaro'), ('Respublika', 'Respublika')], max_length=250, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foydalanuvchilar', verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='nomi',
            field=models.CharField(max_length=250, verbose_name='Ish nomi'),
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='sana',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='turi',
            field=models.CharField(choices=[('Scopus', 'Scopus'), ('Maqola', 'Maqola'), ('Tezis', 'Tezis'), ('EHM guvohnomalar', 'EHM guvohnomalar'), ('patent', 'patent')], max_length=250, verbose_name='Ish turi'),
        ),
        migrations.AlterField(
            model_name='kafedralar',
            name='fakultet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultet', to='app.dekanatlar', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='kafedralar',
            name='mudir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kafedra_mudiri', to='app.foydalanuvchilar', verbose_name='Kafedra mudiri'),
        ),
        migrations.AlterField(
            model_name='kafedralar',
            name='nomi',
            field=models.CharField(max_length=250, verbose_name='Kafedra nomi'),
        ),
        migrations.AlterField(
            model_name='kafedralar',
            name='oqituvchilar',
            field=models.ManyToManyField(blank=True, related_name='kafedra_oqituvchilari', to='app.foydalanuvchilar', verbose_name="O'qituvchilar"),
        ),
        migrations.AlterField(
            model_name='kafedratalablari',
            name='faol',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='kafedratalablari',
            name='ish_turi',
            field=models.CharField(choices=[('Scopus', 'Scopus maqola'), ('Maqola', 'OAK / Xalqaro maqola'), ('Tezis', 'Tezis / Konferensiya'), ('Darslik', 'Darslik'), ('O`quv qo`llanma', 'O`quv qo`llanma'), ('Monografiya', 'Monografiya'), ('Uslubiy ko`rsatma', 'Uslubiy ko`rsatma'), ('EHM guvohnomalar', 'EHM / Patent'), ('Boshqa', 'Boshqa vazifa')], default='Maqola', max_length=100, verbose_name='Ish turi'),
        ),
        migrations.AlterField(
            model_name='kafedratalablari',
            name='kafedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talablar', to='app.kafedralar', verbose_name='Kafedra'),
        ),
        migrations.AlterField(
            model_name='kafedratalablari',
            name='muddati',
            field=models.DateField(blank=True, null=True, verbose_name='Muddati'),
        ),
        migrations.AlterField(
            model_name='kafedratalablari',
            name='mudir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuklagan_talablari', to='app.foydalanuvchilar', verbose_name="Kim qo'ygan"),
        ),
        migrations.AlterField(
            model_name='kafedratalablari',
            name='sarlavha',
            field=models.CharField(max_length=300, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='kafedratalablari',
            name='talab_miqdori',
            field=models.PositiveIntegerField(default=1, help_text="Har bir o'qituvchidan talab qilinadigan soni", verbose_name='Talab miqdori'),
        ),
        migrations.AlterField(
            model_name='kafedratalablari',
            name='tavsif',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='kafedratalablari',
            name='yaratilgan_sana',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='betlar_soni',
            field=models.IntegerField(verbose_name='Betlar soni'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='fayl',
            field=models.FileField(upload_to='oquv_ishlari/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='foreveryone',
            field=models.BooleanField(default=False, verbose_name="Hamma ko'ra oladi"),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='haqida',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='oquv_ishlari_images/', verbose_name='Muqova rasmi'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='ish_mualliflari',
            field=models.TextField(null=True, verbose_name='Hammualliflar'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foydalanuvchilar', verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='nomi',
            field=models.CharField(max_length=250, verbose_name='Ish nomi'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='sana',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='turi',
            field=models.CharField(choices=[('Uslubiy ko`rsatma', 'Uslubiy ko`rsatma'), ('O`quv qo`llanma', 'O`quv qo`llanma'), ('Darslik', 'Darslik'), ('Monografiya', 'Monografiya')], max_length=250, verbose_name='Ish turi'),
        ),
        migrations.AlterField(
            model_name='video_darslar',
            name='foreveryone',
            field=models.BooleanField(default=False, verbose_name="Hamma ko'ra oladi"),
        ),
        migrations.AlterField(
            model_name='video_darslar',
            name='haqida',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='video_darslar',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foydalanuvchilar', verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='video_darslar',
            name='nomi',
            field=models.CharField(max_length=250, verbose_name='Dars nomi'),
        ),
        migrations.AlterField(
            model_name='video_darslar',
            name='sana',
            field=models.DateField(null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='video_darslar',
            name='video',
            field=models.FileField(upload_to='video_darslar/', verbose_name='Video fayl'),
        ),
    ]
