# Generated by Django 6.0.3 on 2026-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_dekanatlar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiy_ishlari',
            name='dgu_raqami',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='DGU / Guvohnoma raqami'),
        ),
    ]
