# Generated by Django 6.0.3 on 2026-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_ilmiy_ishlari_dgu_raqami'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiy_ishlari',
            name='maqola_link',
            field=models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Maqola havolasi (DOI / Link)'),
        ),
    ]
