# Generated by Django 6.0.3 on 2026-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_ilmiy_ishlari_maqola_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_darslar',
            name='video_link',
            field=models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='Video havolasi (YouTube / Link)'),
        ),
        migrations.AlterField(
            model_name='video_darslar',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_darslar/', verbose_name='Video fayl'),
        ),
    ]
